### ISSUE TITLE
Dynamic tuple size

### ISSUE THREAD

**Issue by WolfDan** [ananthakumaran/fdb#4]
Hey, 

Im trying to save list of data (either fixed type or dynamic) in FDB, so far the best option I see is to save them as a FDB tuples, but right now the tuple coder is of fixed size, is there any way to do is dynamic size? Or do I need to create a custom coder? 

Cheers

**Comment by ananthakumaran** [comment]
There is FDB.Coder.Dynamic, it's not documented because I am not sure about the api of this coder. As explained in https://github.com/ananthakumaran/fdb/issues/1#issuecomment-398277498, the main issue is the ambiguity of the value, integer could be encoded in multiple ways etc. This breaks the `encode(x) |> decode == x` symmetry. So dyanmic coder uses tagged values like `{:integer, x}`. This might be awkward to deal with.

Are you using it for key or for value?

**Comment by WolfDan** [comment]
Any example of using it with the Dynamic coder? (seems like custom coder is a better option? 

Right now the use if just for values, but could be using it for both depending on how I decide to serialize the data

**Comment by WolfDan** [comment]
Perfect, thank you so much!
